// class juegoDeMesa {
//     constructor(id, nombreJuego, cantidadMinJugadores,cantidadMaxJugadores,dificultadJuego, imagenJuego, imagenJuego2, linkJuego){
//         this.id = id;
//         this.nombreJuego = nombreJuego;
//         this.cantidadMinJugadores = cantidadMinJugadores;
//         this.cantidadMaxJugadores = cantidadMaxJugadores;
//         this.edadJugadores = edadJugadores;    
//         this.dificultadJuego = dificultadJuego;
//         this.imagenJuego = imagenJuego;
//         this.imagenJuego2 = imagenJuego2;
//         this.linkJuego = linkJuego;
//     }
// }

// const juego001 = new juegoDeMesa ("001", "Hide and seek Safari", 2, 2, 4, "Facil", "https://cf.geekdo-images.com/uQ3pd-xvi0PYeDccBlcHeA__imagepage/img/nbfvCASpnIkh7EtAyeukd5O97bs=/fit-in/900x600/filters:no_upscale():strip_icc()/pic638520.jpg", "https://cf.geekdo-images.com/XpyhYmory1eteD44YtdMJQ__imagepage/img/ryCrY7zrP-Te4tSB_fU5_vt1AIM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic195661.jpg", "https://boardgamegeek.com/boardgame/18262/hide-seek-safari");
// const juego002 = new juegoDeMesa ("002", "Cot Cot Panik", 1, 2, 6, "Moderada", "https://cf.geekdo-images.com/yEs1aYHtID1FSJ3wH8QWqA__original/img/l7FhYYlM20rkFyzxVYZjG6nE0Mk=/0x0/filters:format(jpeg)/pic5908609.jpg", "https://escaleajeux.fr/c/ccpan.jpg", "https://boardgamegeek.com/boardgame/306143/cot-cot-panik")


// console.log(juegoDeMesa)


const juegos = [
    {
        id: "001", 
        nombreJuego: "Hide and seek Safari", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 2,
        edadJugadores: 4, 
        dificultadJuego: "Facil",
        imagenJuego: "https://cf.geekdo-images.com/uQ3pd-xvi0PYeDccBlcHeA__imagepage/img/nbfvCASpnIkh7EtAyeukd5O97bs=/fit-in/900x600/filters:no_upscale():strip_icc()/pic638520.jpg",
        imagenJuego2:"https://cf.geekdo-images.com/XpyhYmory1eteD44YtdMJQ__imagepage/img/ryCrY7zrP-Te4tSB_fU5_vt1AIM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic195661.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/18262/hide-seek-safari",
    },
    {
        id: "002", 
        nombreJuego: "Cot Cot Panik", 
        cantidadMinJugadores: 1,
        cantidadMaxJugadores: 2,
        edadJugadores: 6, 
        dificultadJuego: "Moderada",
        imagenJuego: "https://cf.geekdo-images.com/yEs1aYHtID1FSJ3wH8QWqA__original/img/l7FhYYlM20rkFyzxVYZjG6nE0Mk=/0x0/filters:format(jpeg)/pic5908609.jpg",
        imagenJuego2: "https://escaleajeux.fr/c/ccpan.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/306143/cot-cot-panik", 
    },
    {
        id: "003", 
        nombreJuego: "Potion Class", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 2,
        edadJugadores: 6, 
        dificultadJuego: "Dificil", 
        imagenJuego: "https://cf.geekdo-images.com/nSdEY4yDRfnQX38JYzi9Xg__imagepagezoom/img/E-ymDykdZosKwE0YGejhhABlbRE=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic4973525.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/NgB3CZUss7L5m9s-zHnE6g__imagepage/img/hz6JeuGXVWIa_6P2OEuzCnnoA10=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4418449.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/260322/potions-class", 
    },
    {
        id: "004", 
        nombreJuego: "Lunes", 
        cantidadMinJugadores: 1,
        cantidadMaxJugadores: 1,
        edadJugadores: 10, 
        dificultadJuego: "Facil", 
        imagenJuego: "https://cf.geekdo-images.com/v3-bi_nn0iQnfvUHDEGuwA__imagepagezoom/img/vW9kqQs65l1LDJpuilAQwnlaO-s=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic4300851.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/RuJAsftuYJFAxS3GheTZvQ__imagepage/img/RdX3iTJsXBDewgJQItvHDMwQRrg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4398095.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/259393/lunes", 
    },
    {
        id: "005", 
        nombreJuego: "Hive", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 2,
        edadJugadores: 9, 
        dificultadJuego: "Moderada", 
        imagenJuego: "https://cf.geekdo-images.com/fQe85tsBZoH6ibPnm1k1UA__imagepage/img/OtZYo1Dn9EVlZu3KTG18GcgAB6Y=/fit-in/900x600/filters:no_upscale():strip_icc()/pic791151.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/Lr-mR9i6SD2-0Q9odND5uQ__imagepage/img/y3KUINeczKqfpYmkwVkRQzWVkvg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic114606.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/2655/hive", 
    },
    {
        id: "006", 
        nombreJuego: "Twiligth Struggle", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 2,
        edadJugadores: 13, 
        dificultadJuego: "Dificil", 
        imagenJuego: "https://cf.geekdo-images.com/pNCiUUphnoeWOYfsWq0kng__imagepage/img/BWy9XaudHc_YnHCrzFc3cINAhvw=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3530661.jpg" ,
        imagenJuego2: "https://cf.geekdo-images.com/3xtaGglJAnMe4LdItL1fuQ__imagepage/img/nfWS98XYPBb8CsFvpl6X74mOi6w=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2726905.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/12333/twilight-struggle",
    },
    {
        id: "007", 
        nombreJuego: "Gwent: Monsters and Scoia'tael", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 2,
        edadJugadores: 14, 
        dificultadJuego: "Facil", 
        imagenJuego: "https://cf.geekdo-images.com/MB6d2y0WmG3j2jH_Bz7Vpw__imagepage/img/TRtOIibL6ra6DtljwPZk6ut2ayU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2794272.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/WxV3wn_VyfvI6cYxwbpdkw__imagepage/img/Lf0_WWkkAqVn_FNwZ7XC5rN07Hs=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6309800.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/178147/gwent-monsters-and-scoiatael",
    },
    {
        id: "008", 
        nombreJuego: "One Deck Dungeon", 
        cantidadMinJugadores: 1,
        cantidadMaxJugadores: 2,
        edadJugadores: 14, 
        dificultadJuego: "Moderada", 
        imagenJuego: "https://cf.geekdo-images.com/quvyGpE7kwbd2Mt1H5iLwQ__imagepage/img/fi9Dgl4uplKNN75gbAYFWXwilbI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3019101.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/wcWacyRRyA9DCc4HDCU3jw__imagepage/img/u_0sGPHL_UnehBA-souW7TLZrno=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4045185.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/179275/one-deck-dungeon",
    },
    {
        id: "009", 
        nombreJuego: "Arkham Horror LCG", 
        cantidadMinJugadores: 1,
        cantidadMaxJugadores: 2,
        edadJugadores: 14, 
        dificultadJuego: "Dificil", 
        imagenJuego: "https://cf.geekdo-images.com/RdCWCXPnBGSxoOhk5Hkq_g__imagepage/img/IjAnsFhA0onPRgYnLLsRG3PZHcI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6530423.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/fIJKjpYHK_ZhL7-ZTOegvg__imagepage/img/ao7A8RyH5zNy-Zuih8BWtaHPMuI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4885955.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/205637/arkham-horror-card-game",
    },
    {
        id: "010", 
        nombreJuego: "Batameuh", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 4,
        edadJugadores: 4, 
        dificultadJuego: "Facil", 
        imagenJuego: "https://cf.geekdo-images.com/5oC_ETrxufOxVxfCCklHxQ__imagepage/img/TKOlU5ds3sJqAQuhXf_5WhrJNUg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic459441.jpg",
        imagenJuego2: "http://2.bp.blogspot.com/_e6pt6jcMYKs/S3gPEo9FkwI/AAAAAAAAAGg/mcdu9BpkAsY/s1600/IMG_0099.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/41640/batameuh",
    },
    {
        id: "011", 
        nombreJuego: "My First Stone Age", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 4,
        edadJugadores: 5, 
        dificultadJuego: "Moderada", 
        imagenJuego: "https://cf.geekdo-images.com/11Z-S3LYwZVgn7adwvMg_g__imagepage/img/WT1kkSiEZO4BUZJojduOrQ9XfYE=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2830962.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/Gmm5zbGtdSH2448et7QSRg__imagepage/img/iwFfvAmF1EVPzgv_eGhrNYJpIXU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3004881.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/191004/my-first-stone-age",
    },
    {
        id: "012", 
        nombreJuego: "Mice & Mistic", 
        cantidadMinJugadores: 1,
        cantidadMaxJugadores: 4,
        edadJugadores: 7, 
        dificultadJuego: "Dificil", 
        imagenJuego: "https://cf.geekdo-images.com/pZFrbWXBzrkxqOotg05D9Q__imagepage/img/8DDUzC_cfdNq-atVwcATQKre3Qs=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1312072.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/_wsOqXCOktvb7uHeyou9og__imagepage/img/fsmNfaANLAzTvd8l9pkhAfsp-4k=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1387080.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/124708/mice-and-mystics",
    },
    {
        id: "013", 
        nombreJuego: "Herbaceous", 
        cantidadMinJugadores: 1,
        cantidadMaxJugadores: 4,
        edadJugadores: 8, 
        dificultadJuego: "Facil", 
        imagenJuego: "https://cf.geekdo-images.com/xkQEg3m5ePqjlffYsPahUg__imagepage/img/oAj2JPFpmvcfXN2xOulzpPWPN4w=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3048690.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/w3ZMeshmv1j_iMATbY-VEQ__imagepage/img/PluKp3Pxo7YWbM2fBcZSBEdJ0Zk=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3677174.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/195314/herbaceous",
    },
    {
        id: "014", 
        nombreJuego: "Catan", 
        cantidadMinJugadores: 3,
        cantidadMaxJugadores: 4,
        edadJugadores: 10, 
        dificultadJuego: "Moderada", 
        imagenJuego: "https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__imagepage/img/M_3Vg1j2HlNgkv7PL2xl2BJE2bw=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2419375.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/4Zr2B1zIgCM9qZfKhZoisQ__imagepage/img/kXfQ2kYjDENgXmRcXYrBcmuhf4U=/fit-in/900x600/filters:no_upscale():strip_icc()/pic133885.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/13/catan",
    },
    {
        id: "015", 
        nombreJuego: "Root", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 4,
        edadJugadores: 10, 
        dificultadJuego: "Dificil", 
        imagenJuego: "https://cf.geekdo-images.com/JUAUWaVUzeBgzirhZNmHHw__imagepage/img/ZF-dta5ffawuKAkAt2LB-QTIv5M=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4254509.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/PQvaJX04og2izBVPiD25mA__imagepage/img/toD-fUqeGuilEKv6h8NqzppLgzM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4241193.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/237182/root",
    },
    {
        id: "016", 
        nombreJuego: "Spirit of the Forest", 
        cantidadMinJugadores: 1,
        cantidadMaxJugadores: 4,
        edadJugadores: 14, 
        dificultadJuego: "Facil", 
        imagenJuego: "https://cf.geekdo-images.com/wyBIWeEvycBcGeEfc5HWwg__imagepage/img/STVKpLsF1QUSSm8euHtrSJJ3-tY=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3862634.png",
        imagenJuego2: "https://cf.geekdo-images.com/M3K7vYc-AB2jA5QfOBwTAg__imagepage/img/2iqoMMSrrw6LDbtTwLpSi9JEf6c=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4343832.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/235375/spirits-forest",
    },
    {
        id: "017", 
        nombreJuego: "Pandemic Reign of Cthulhu", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 4,
        edadJugadores: 14, 
        dificultadJuego: "Moderada", 
        imagenJuego: "https://cf.geekdo-images.com/rwNaEQfzABp7dkpnwn1Ksw__imagepage/img/WUXox5-iSeX_LIfN-cfWaG2hmTk=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2866737.png",
        imagenJuego2: "https://cf.geekdo-images.com/H230wmBzriZB3tqF_4mUtA__imagepage/img/Xg06RjUKhL-Ti90ycuajFivaCs4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2891581.png",
        linkJuego: "https://boardgamegeek.com/boardgame/192153/pandemic-reign-cthulhu",
    },
    {
        id: "018", 
        nombreJuego: "Dark Souls Board Game", 
        cantidadMinJugadores: 1,
        cantidadMaxJugadores: 4,
        edadJugadores: 14, 
        dificultadJuego: "Dificil", 
        imagenJuego: "https://cf.geekdo-images.com/mHQMnDL317AKXCt9LojYxw__imagepage/img/KRpJbdueGxcxhpexCAvpfY1VDgU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3784353.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/oN9wN4AotlA-gzY00tBTtg__imagepage/img/JlCEhIoj2L_Rw1B4RdgxL01MwU0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3221207.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/197831/dark-souls-board-game",
    },
    {
        id: "019", 
        nombreJuego: "Fantasma Blitz Junior", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 6,
        edadJugadores: 4, 
        dificultadJuego: "Facil", 
        imagenJuego: "https://cf.geekdo-images.com/uZ22xeX-BaAi48tlWei5pA__imagepage/img/7gRpDgaZzzkLOVVKJxqyAEC7cLQ=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3944113.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/x1e5kPDn62Ni2PexTpVZIQ__imagepage/img/6FEnJEFbIQDZ2EzPAA9opOVOZ5A=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5390944.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/244702/geistesblitz-junior",
    },
    {
        id: "020", 
        nombreJuego: "Polilla Tramposa", 
        cantidadMinJugadores: 3,
        cantidadMaxJugadores: 5,
        edadJugadores: 7, 
        dificultadJuego: "Moderada", 
        imagenJuego: "https://cf.geekdo-images.com/8M51tLQxA7QJDrhmJWPvoQ__imagepage/img/S9-axeKJyHeDVAsNmOICBeZib7s=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2266547.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/rEWqvsXaAACoYhxaHEW59g__imagepage/img/WHB1FlencPf8Klro-tQ2RmiAZtU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1575436.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/105593/cheating-moth",
    },
    {
        id: "021", 
        nombreJuego: "Carcassone", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 5,
        edadJugadores: 7, 
        dificultadJuego: "Dificil", 
        imagenJuego: "https://cf.geekdo-images.com/okM0dq_bEXnbyQTOvHfwRA__imagepage/img/axGbn7f0x6UUb07DmzX9hg5TwIo=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6544250.png",
        imagenJuego2: "https://cf.geekdo-images.com/GekIJjlGckEp9dGzBot7-Q__imagepage/img/lgXgSQ05OoISiVFeRcyxpGYS7tQ=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1581446.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/822/carcassonne",
    },
    {
        id: "022", 
        nombreJuego: "Dixit", 
        cantidadMinJugadores: 3,
        cantidadMaxJugadores: 6,
        edadJugadores: 8, 
        dificultadJuego: "Facil", 
        imagenJuego: "https://cf.geekdo-images.com/J0PlHArkZDJ57H-brXW2Fw__imagepage/img/j3bmkyVXJ2tOOXQzARtHqT__vzY=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6738336.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/qE5nZ6mub_hfsuFMiYJ2-Q__imagepage/img/lDvsXMt2oFW7bRZGuzrr-aNuWMM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic410739.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/39856/dixit",
    },
    {
        id: "023", 
        nombreJuego: "Coup: Reformation", 
        cantidadMinJugadores: 2,
        cantidadMaxJugadores: 10,
        edadJugadores: 10, 
        dificultadJuego: "Moderada", 
        imagenJuego: "https://cf.geekdo-images.com/-Pnt6sTdrbrGhCH0uPvdSQ__imagepage/img/3d6eFb4dVZf88pTo1uUx07tK7AA=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1978817.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/L9uTvkiSZIQ9FEX7-3OjHg__imagepage/img/eT8FPySvB0nhz4ht0SRwtzD2bPE=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2256714.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/148931/coup-reformation",
    },
    {
        id: "024", 
        nombreJuego: "Saboteur: The lost mines", 
        cantidadMinJugadores: 3,
        cantidadMaxJugadores: 9,
        edadJugadores: 10, 
        dificultadJuego: "Dificil", 
        imagenJuego: "https://cf.geekdo-images.com/ri8mcs_j26dGRxA5e2xITQ__imagepage/img/YYBlFGsMP_nWjujKZJd7FXoepMo=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4496800.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/RyTxLIhfAO58uwuxhYdVpg__imagepage/img/thNG9qAJQ_6qv2RBHq5OR9xUbsQ=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4294236.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/245214/saboteur-lost-mines",
    },
    {
        id: "025", 
        nombreJuego: "Finger guns at high noon", 
        cantidadMinJugadores: 3,
        cantidadMaxJugadores: 8,
        edadJugadores: 14, 
        dificultadJuego: "Facil", 
        imagenJuego: "https://cf.geekdo-images.com/U507dP9ic5BAXuvZkwTi_w__imagepage/img/bE1R6fR7KVlIaKR8bsDurOLj0SA=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4652450.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/yn4uwQV2aGD_bm0b5zdxoA__imagepage/img/WrBlNAI9aHGzSTaOGoRshFySFmQ=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5036656.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/276296/finger-guns-high-noon",
    },
    {
        id: "026", 
        nombreJuego: "Sagrada", 
        cantidadMinJugadores: 1,
        cantidadMaxJugadores: 4,
        edadJugadores: 14, 
        dificultadJuego: "Moderada", 
        imagenJuego: "https://cf.geekdo-images.com/PZt3EAAGV3dFIVuwMR0AEw__imagepage/img/F8DS3hdZfVIcxVpPSZV7DMLrPJ4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3525224.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/63QeHkCdBdUoHfqugCQ0Ng__imagepage/img/KRGX3ryUi8e6DSvROQiXo15YSG0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3666165.jpg",
        linkJuego: "https://boardgamegeek.com/boardgame/199561/sagrada",
    },
    {
        id: "027", 
        nombreJuego: "Mansiones de la locura", 
        cantidadMinJugadores: 1,
        cantidadMaxJugadores: 5,
        edadJugadores: 14, 
        dificultadJuego: "Dificil", 
        imagenJuego: "https://cf.geekdo-images.com/LIooA9bTdjnE9qmhjL-UFw__imagepage/img/nhF-Ys7IOrSMNwJVZSjMV2iVjXo=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3118622.jpg",
        imagenJuego2: "https://cf.geekdo-images.com/m9ZedNP_8LjWTwlSsrvY3w__imagepage/img/Yk3VjpSAxk3RrkJVb_HeH4FUgzY=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3112719.png",
        linkJuego: "https://boardgamegeek.com/boardgame/205059/mansions-madness-second-edition",
    },
];